Changed shource so that flags must come before the file, not after.
Signed-off-by: Oliver Isaac <oisaac@gmail.com>

diff --git a/shource b/shource
--- a/shource
+++ b/shource
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 # source code generated using shource: https://github.com/oliverisaac/shource
-# vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4
+# vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4 ft=sh:
 
 set -e # Exit on any error. Use `COMMAND || true` to nullify
 set -E # Functions inherit error trap
@@ -35,6 +35,7 @@ function parse_args()
     done
 
     local boolean_regex=$( IFS='|'; echo "${boolean_flags[*]}" )
+    boolean_regex="^--(no-)?(${boolean_regex})(=(true|false))?$"
 
     local populate_args=false
     declare -g -a _args=()
@@ -55,8 +56,22 @@ function parse_args()
         key=""
         value=true
         # Boolean flags
-        if [[ ${#boolean_flags[@]} -gt 0 ]] && [[ $this_arg =~ ^--(${boolean_regex})$ ]]; then
-            key="${BASH_REMATCH[1]}"
+        if [[ ${#boolean_flags[@]} -gt 0 ]] && [[ $this_arg =~ $boolean_regex ]]; then
+            key="${BASH_REMATCH[2]}"
+
+            if [[ ${BASH_REMATCH[4]} == "false" ]]; then
+                if [[ ${BASH_REMATCH[1]} == "no-" ]]; then
+                    value=true
+                else
+                    value=false
+                fi
+            else
+                if [[ ${BASH_REMATCH[1]} == "no-" ]]; then
+                    value=false
+                else
+                    value=true
+                fi
+            fi
         elif [[ $this_arg =~ ^--([^=]+)=(.*)$ ]]; then
             key="${BASH_REMATCH[1]}"
             value="${BASH_REMATCH[2]}"
@@ -136,7 +151,7 @@ function log()
         local message="${@}"
 
         if [[ ${JSON_LOG_FORMAT:-false} == "false" ]]; then
-            echo "$message [log $level]: $message" >&2
+            echo "$time [log $level]: $message" >&2
         else
             time=$( date -u +"%Y-%m-%dT%H:%M:%S.%3NZ" )
             json_print time:s "$time" level:d "$level" msg:s "$message" >&2
@@ -163,8 +178,15 @@ function _on_error()
     local lineno=$1
     shift
     local pipe_fails=( "${@}" )
-    echo "ERROR (${pipe_fails[@]}) on line $1: Most recent call last:" >&2
+    echo "ERROR (${pipe_fails[@]}) on line $lineno: Most recent call last:" >&2
     _print_stack >&2
+    local x
+    for x in ${pipe_fails[@]}; do
+        if [[ $x -ne 0 ]]; then
+            exit $x
+        fi
+    done
+    exit 1
 }
 
 
@@ -227,13 +249,18 @@ function main()
     local source="$1"
     local create="$2"
     local overwrite="$3"
-    local no_print_tag="$4"
+    local print_tag="$4"
     local run="$5"
-    local no_print_shebang="$6"
-    local no_make_exec="$7"
+    local print_shebang="$6"
+    local make_exec="$7"
     shift 7
     local args=( "${@}" )
 
+    local run_default=false
+    if [[ $run == "default" ]]; then
+        run=true
+        run_default=true
+    fi
 
     local target_dir=$( dirname "$source" )
     target_dir=$( cd $target_dir && pwd -P )
@@ -264,10 +291,6 @@ function main()
     local temp_write=$(mktemp)
 
     local line_index=0
-    local print_tag=true
-    if $no_print_tag; then
-        print_tag=false
-    fi
 
     local print_this_line=true
     local func_path
@@ -278,7 +301,7 @@ function main()
         local regex='^shource .+\(\) *$'
         if [[ $line =~ $regex ]]; then
             if func_path=$( shource_to_filepath "$line" ); then
-                "$self" "$func_path" --no-print-tag --no-print-shebang --no-make-exec
+                /usr/bin/env bash "$self" --no-print-tag --no-print-shebang --no-make-exec --no-run "$func_path" 
                 continue
             else
                 log 0 "ERROR: You tried to shource $func_name but it does not exist in $self_dir!"
@@ -287,8 +310,12 @@ function main()
         fi
 
         if [[ $line_index == 1 ]] && [[ $line =~ ^#! ]]; then
-            if $no_print_shebang; then
+            if ! $print_shebang; then
                 print_this_line=false
+            fi
+
+            if [[ $line =~ \#!.*shource ]]; then
+                line="#!/usr/bin/env bash"
             fi
         fi
 
@@ -301,21 +328,33 @@ function main()
         echo "$tag" | sed -i"" -e '1 r /dev/stdin' "$temp_write"
     fi
 
-    if ! $run; then
-        cat "$temp_write" > "$write_target"
+    if $create || ! $run; then
+        local write_to_file=false
+        # If we are writing to stdout or if the file will actually make a change, then write the file
+        if [[ $write_target == $default_write_target ]]; then
+            write_to_file=true
+        elif ! ( diff -q "$write_target" "$temp_write" 2>/dev/null ); then
+            write_to_file=true
+        fi
 
-        if ! $no_make_exec && [[ $write_target != $default_write_target ]]; then
+        if $write_to_file; then
+            cat "$temp_write" > "$write_target"
+        fi
+
+        if $make_exec && [[ $write_target != $default_write_target ]]; then
             chmod +x "$write_target"
         fi
     fi
 
-    if $run; then
+    # IF the user explicitly asked to run then run. If they didn't ask to create, then run
+    local return_value=0
+    if ( ! $run_default && $run ) || ( ! $create && $run ); then
         chmod +x "$temp_write"
-        /usr/bin/env bash "$temp_write" "${args[@]}"
+        /usr/bin/env bash "$temp_write" "${args[@]}" || return_value=$?
     fi
 
     rm "$temp_write"
-    return 0
+    return $return_value
 }
 
 
@@ -327,12 +366,25 @@ function _display_help()
 EOF
 }
 
+all_args=( "${@}" )
+shource_args=()
+command_args=()
+
+for x in "${all_args[@]}"; do
+    shource_args+=( "$x" )
+    shift
+    if [[ -f "$x" ]]; then
+        break
+    fi
+done
+command_args=( "${@}" )
+
 # Check if any of the args are a cry for help
-if echo "${@}" | grep -q -wiEe "-h|--help|help"; then
+if echo "${shource_args[@]}" | grep -q -wiEe "-h|--help|help"; then
     _display_help
     exit 4
 fi
 
 # Edit parse args to indicate which flags are boolean. Then pass each of those arguments to main
-parse_args run no_make_exec no_print_tag no_print_shebang create force -- "${@}"
-main "${_args[0]}" "${create:-false}" "${force:-false}" "${no_print_tag:-false}" "${run:-false}" "${no_print_shebang:-false}" "${no_make_exec:-false}" "${_args[@]:1}"; exit $?
+parse_args run make_exec print_tag print_shebang create force -- "${shource_args[@]}"
+main "${_args[0]}" "${create:-false}" "${force:-false}" "${print_tag:-true}" "${run:-default}" "${print_shebang:-true}" "${make_exec:-true}" "${command_args[@]}"; exit $?
diff --git a/shources/traps b/shources/traps
--- a/shources/traps
+++ b/shources/traps
@@ -19,8 +19,15 @@ function _on_error()
     local lineno=$1
     shift
     local pipe_fails=( "${@}" )
-    echo "ERROR (${pipe_fails[@]}) on line $1: Most recent call last:" >&2
+    echo "ERROR (${pipe_fails[@]}) on line $lineno: Most recent call last:" >&2
     _print_stack >&2
+    local x
+    for x in ${pipe_fails[@]}; do
+        if [[ $x -ne 0 ]]; then
+            exit $x
+        fi
+    done
+    exit 1
 }
 
 shource _print_stack()
