Added envirnment viarable to parse_args using the ^ symbol

diff --git a/shources/parse_args b/shources/parse_args
--- a/shources/parse_args
+++ b/shources/parse_args
@@ -30,7 +30,7 @@ function parse_these()
         local arg_type=$BOOL_TYPE
 
         flag_regex='^([!])?([a-zA-Z0-9_-]+)(:([a-zA-Z]))?'
-        default_help_regex="(@(.*))?(/(.*))"
+        default_help_regex='((\^([a-zA-Z_]+))*)(@(.*))?(/(.*))'
         regex_bool="${flag_regex}:b(ool(ean)?)?$default_help_regex$"
         regex_array="${flag_regex}:a(rr(ay)?)?$default_help_regex$"
         regex_string="${flag_regex}:s(tr(ing)?)?$default_help_regex$"
@@ -44,7 +44,7 @@ function parse_these()
             log 0 "bool regex: $regex_bool"
             log 0 "array regex: $regex_array"
             log 0 "string regex: $regex_string"
-            log 0 "Proper format for argument config: !long_flag:short_flag:type@default/help_message"
+            log 0 "Proper format for argument config: !long_flag:short_flag:type^ENV_VAR@default/help_message"
             log 0 "help_message is required, use ! to indicate required"
             log -1 "Error with pars args, unexpected config: $this_arg"
         fi
@@ -57,8 +57,11 @@ function parse_these()
         var_name="${long_flag}"
 
         short_flag="${BASH_REMATCH[4]}"
-        default_value="${BASH_REMATCH[8]}"
-        help_text="${BASH_REMATCH[10]}"
+        env_vars="${BASH_REMATCH[7]}"
+        default_value="${BASH_REMATCH[11]}"
+        help_text="${BASH_REMATCH[13]}"
+
+        env_vars=( ${env_vars//^/ } )
 
         if $required && [[ -z $default_value ]]; then
             required_flags[$var_name]=false
@@ -99,8 +102,18 @@ function parse_these()
 
         local required_message="Optional"
         $required && required_message="Required"
-        b64help=$( printf "   %-15s : %s (default: %s) %s" "--${long_flag}${short_flag:+, -}${short_flag}" "$help_text" "$default_value" "$required_message" )
+        local env_var_help=" "
+        if [[ ${#env_vars[@]} -gt 0 ]]; then
+            env_var_help=" Env: [ ${env_vars[*]} ] "
+        fi
+        b64help=$( printf "   %-15s : %s (default: %s)%s%s" "--${long_flag//_/-}${short_flag:+, -}${short_flag}" "$help_text" "$default_value" "$env_var_help" "$required_message" )
         b64help=$( echo "$b64help" | base64 -w0 )
+        for var in "${env_vars[@]}"; do
+            declare -n env_var=$var
+            if [[ "${env_var:-}" != "" ]]; then
+                default_value="$env_var"
+            fi
+        done
 
         b64default=$( echo "$default_value" | base64 -w0 )
 
@@ -261,8 +274,7 @@ function parse_these()
         fi
     done
     if [[ ${#missing_flags[@]} -gt 0 ]]; then
-        log -1 "Missing these required flags: ${missing_flags[@]}"
-        exit 1
+        printf "%s:%s:%s:\n" "$ERROR_TYPE" "error" "$( base64 -w0 <<< "Missing these required flags: ${missing_flags[@]}"  )"
     fi
 }
 export -f parse_these
@@ -270,8 +282,9 @@ export -f parse_these
 function parse_args()
 {
     local reset_x=false
-    local ARRAY_TYPE=array BOOL_TYPE=boolean STRING_TYPE=string
+    local ARRAY_TYPE=array BOOL_TYPE=boolean STRING_TYPE=string ERROR_TYPE=error
     local help_texts=()
+    local error=false
 
     if [[ $- =~ x ]]; then
         reset_x=true
@@ -327,16 +340,20 @@ function parse_args()
             else
                 declare -g "$key"="$value"
             fi
+        elif [[ "$kind" == "$ERROR_TYPE" ]]; then
+            log -1 "$value"; 
+            error=true
         fi
     done <<< "$to_parse"
 
     $reset_x && set -x || true
 
-    if ${help:-false}; then
+    if ${help:-false} || $error; then
         echo
         echo "Help for $( basename $0 )" 
         printf "%s\n" "${help_texts[@]}" | sort
-        exit 0
+        echo
+        $error && exit 1 || exit 0
     fi >&2
 
     return 0
